// File generated by FlutterFire CLI / custom setup for Klamy.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6fj1bLNbVZjTSi1lV5SvIkKLf0rGQY4Q',
    appId: '1:1060317334078:web:c168908b20cf8b693a5f6f',
    messagingSenderId: '1060317334078',
    projectId: 'klamy-8789e',
    authDomain: 'klamy-8789e.firebaseapp.com',
    databaseURL: 'https://klamy-8789e-default-rtdb.firebaseio.com',
    storageBucket: 'klamy-8789e.firebasestorage.app',
    measurementId: 'G-SDMMFY4B2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAszPqHaM7ccKxCuUzEv0JXYP8aX4id524',
    appId: '1:1060317334078:android:2e4f49f2309083c33a5f6f',
    messagingSenderId: '1060317334078',
    projectId: 'klamy-8789e',
    databaseURL: 'https://klamy-8789e-default-rtdb.firebaseio.com',
    storageBucket: 'klamy-8789e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzqBE7M-sL8XIRC4VSZjlY3cB3562Vwyo',
    appId: '1:1060317334078:ios:5d670bfc4850e32b3a5f6f',
    messagingSenderId: '1060317334078',
    projectId: 'klamy-8789e',
    databaseURL: 'https://klamy-8789e-default-rtdb.firebaseio.com',
    storageBucket: 'klamy-8789e.firebasestorage.app',
    iosBundleId: 'in.asrvtech.klamy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzqBE7M-sL8XIRC4VSZjlY3cB3562Vwyo',
    appId: '1:1060317334078:ios:5d670bfc4850e32b3a5f6f',
    messagingSenderId: '1060317334078',
    projectId: 'klamy-8789e',
    databaseURL: 'https://klamy-8789e-default-rtdb.firebaseio.com',
    storageBucket: 'klamy-8789e.firebasestorage.app',
    iosBundleId: 'in.asrvtech.klamy',
  );
}
